FROM node:24-slim AS build

WORKDIR /app

COPY /package*.json .

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/

EXPOSE 80

CMD ["nginx"]
